AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Lambda1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda1-secret-access
      Handler: index.handler
      Runtime: python3.9
      CodeUri: lambda1/
      Policies:
        - SecretsManagerReadWrite

  Lambda2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda2-email
      Handler: index.handler
      Runtime: python3.9
      CodeUri: lambda2/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: "*"
