name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create builds directory
        run: mkdir -p builds

      - name: Zip secret_lambda
        run: |
          cd secret_lambda
          zip -r ../builds/secret_lambda.zip .

      - name: Zip email_template
        run: |
          cd email_template
          zip -r ../builds/email_template.zip .

      # Your existing delete IAM roles, policies, lambda functions steps...

      - name: Delete existing lambda3-role IAM role if exists
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          set -e
          if aws iam get-role --role-name lambda3-role >/dev/null 2>&1; then
            echo "Deleting lambda3-role..."
            for policy_arn in $(aws iam list-attached-role-policies --role-name lambda3-role --query 'AttachedPolicies[].PolicyArn' --output text); do
              aws iam detach-role-policy --role-name lambda3-role --policy-arn "$policy_arn"
            done
            aws iam delete-role --role-name lambda3-role
          fi

      - name: Import lambda1-role
        run: terraform import aws_iam_role.lambda1_role lambda1-role || echo "lambda1-role already imported or failed"
        working-directory: ${{ github.workspace }}/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Import lambda2-role
        run: terraform import aws_iam_role.lambda2_role lambda2-role || echo "lambda2-role already imported or failed"
        working-directory: ${{ github.workspace }}/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ github.workspace }}/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ github.workspace }}/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
